import Head from "next/head";
import Footer from "../components/layout/Footer";
import HomeHeader from "../components/layout/HomeHeader";
import Section from "../components/layout/Section";
import ProductList, {
  ProductListProps,
} from "../components/product/ProductList";
import strings from "../strings";

const dummy_data: ProductListProps["products"] = [
  {
    title: "מוצר 1",
    description: strings.ABOUT_ME,
    id: "1",
    coverImageUrl: "https://picsum.photos/seed/picsum/300/300",
  },
  {
    title: "מוצר 2",
    description: strings.ABOUT_ME,
    id: "1",
    coverImageUrl: "https://picsum.photos/seed/picsum/300/300",
  },
  {
    title: "מוצר 3",
    description: strings.ABOUT_ME,
    id: "1",
    coverImageUrl: "https://picsum.photos/seed/picsum/300/300",
  },
  {
    title: "מוצר 4",
    description: strings.ABOUT_ME,
    id: "1",
    coverImageUrl: "https://picsum.photos/seed/picsum/300/300",
  },
];

export default function Home() {
  return (
    <div className="flex flex-col items-stretch">
      <Head>
        <title>Monopolika</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeHeader />
      <main>
        <Section className="py-6" title={strings.MY_PRODUCTS}>
          <ProductList
            className="grid sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-4 max-w-[80%] mx-auto"
            products={dummy_data}
          />
        </Section>
      </main>
      <Footer />
    </div>
  );
}
