import Head from "next/head";
import ProductCard from "../components/product/ProductCard";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Monopolika</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-60 h-40">
        <ProductCard variant="pink">
          שלום שלום
        </ProductCard>
      </main>
    </div>
  );
}
